-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.company
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT company_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.company
    OWNER to postgres;

ALTER TABLE IF EXISTS public.company
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.company TO anon;

GRANT ALL ON TABLE public.company TO authenticated;

GRANT ALL ON TABLE public.company TO postgres;

GRANT ALL ON TABLE public.company TO service_role;
CREATE POLICY "Enable read access for all users"
    ON public.company
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
